# Generated by Django 6.1 on 2026-08-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSkill',
            fields=[
                ('assignment_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_skill_requirements', to='core.assignment')),
                ('project_skill_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_skills', to='core.projectskillrequirement')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('assignment', 'project_skill_requirement'), name='unique_assignment_skill_requirement')],
            },
        ),
    ]
