# Generated by Django 6.1 on 2026-09-03 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_assignmentskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectskillrequirement',
            name='estimated_effort_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated total number of project hours associated with this skill requirement.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='projectskillrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_effort_hours__gte', 0)), name='projectskillrequirement_effort_hours_non_negative'),
        ),
    ]
